# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-08 02:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DBMode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='GlobalConfiguration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('maintananceWindowHour', models.IntegerField(default=10)),
                ('trafficPercentageUnderMaitananceWindow', models.FloatField(default=1)),
            ],
        ),
    ]
