# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-08 07:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Common', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NetworkInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('defaultSIGTRANLinkSpeed', models.IntegerField()),
                ('defaultSIGTRANLinkNumber', models.IntegerField()),
                ('maxSIGTRANPortUtil', models.FloatField()),
            ],
        ),
    ]
