# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-08 08:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Common', '0002_networkinfo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dbmode',
            name='name',
            field=models.CharField(choices=[('rtdb', 'RTDB'), ('ndb', 'NDB')], default='rtdb', max_length=10),
        ),
    ]
