# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-15 06:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Common', '0003_auto_20170608_1651'),
    ]

    operations = [
        migrations.AddField(
            model_name='globalconfiguration',
            name='releaseAppMemoryImpact',
            field=models.FloatField(default=0.1),
        ),
        migrations.AddField(
            model_name='globalconfiguration',
            name='releaseCPUImpact',
            field=models.FloatField(default=0.05),
        ),
        migrations.AddField(
            model_name='globalconfiguration',
            name='releaseDBMemoryImpact',
            field=models.FloatField(default=0.1),
        ),
        migrations.AddField(
            model_name='globalconfiguration',
            name='reservedCPURatio',
            field=models.FloatField(default=0.15),
        ),
    ]
