# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-19 08:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Common', '0004_auto_20170615_1434'),
    ]

    operations = [
        migrations.AddField(
            model_name='globalconfiguration',
            name='releaseCountCPUImpact',
            field=models.FloatField(default=0.05),
        ),
    ]
