# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-03 08:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0006_globalconfiguration_releasesequence'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='globalconfiguration',
            name='releaseSequence',
        ),
    ]
