# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-05 14:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0008_auto_20171019_1447'),
    ]

    operations = [
        migrations.AddField(
            model_name='globalconfiguration',
            name='ndbRTDBCostRatio',
            field=models.FloatField(default=1.3),
        ),
    ]
