# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-22 02:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CPU',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=16)),
                ('coreNumber', models.IntegerField()),
                ('overallCapacity', models.FloatField()),
                ('singleThreadCapacity', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='CPUClientList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clientNumber', models.IntegerField()),
                ('capacityRatio', models.FloatField()),
                ('CPU', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Hardware.CPU')),
            ],
        ),
        migrations.CreateModel(
            name='CPUHyperthread',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hyperthreadEnabled', models.BooleanField()),
                ('capacityRatio', models.FloatField()),
                ('CPU', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Hardware.CPU')),
            ],
        ),
        migrations.AddField(
            model_name='cpuclientlist',
            name='CPUHyperthread',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Hardware.CPUHyperthread'),
        ),
    ]
