# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-23 08:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hardware', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CPUList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cpuNumber', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='HardwareConfiguration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CPUNumber', models.IntegerField()),
                ('memory', models.IntegerField()),
                ('clientNumber', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='HardwareModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('maxNodeNumber', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='HardwareType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=24)),
            ],
        ),
        migrations.CreateModel(
            name='MemoryList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('memory', models.IntegerField()),
            ],
        ),
        migrations.RemoveField(
            model_name='cpuhyperthread',
            name='CPU',
        ),
        migrations.RemoveField(
            model_name='cpuclientlist',
            name='CPUHyperthread',
        ),
        migrations.AddField(
            model_name='cpu',
            name='HTCapacityRatio',
            field=models.FloatField(default=1),
        ),
        migrations.AddField(
            model_name='cpu',
            name='VMCapacityRatio',
            field=models.FloatField(default=1),
        ),
        migrations.AddField(
            model_name='cpu',
            name='defaultClientNumber',
            field=models.IntegerField(default=16),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cpu',
            name='hyperthreadEnabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='cpu',
            name='virtualization',
            field=models.BooleanField(default=False),
        ),
        migrations.DeleteModel(
            name='CPUHyperthread',
        ),
        migrations.AddField(
            model_name='memorylist',
            name='CPU',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Hardware.CPU'),
        ),
        migrations.AddField(
            model_name='hardwaremodel',
            name='CPU',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Hardware.CPU'),
        ),
        migrations.AddField(
            model_name='hardwaremodel',
            name='HardwareType',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Hardware.HardwareType'),
        ),
        migrations.AddField(
            model_name='hardwareconfiguration',
            name='HardwareModel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Hardware.HardwareModel'),
        ),
        migrations.AddField(
            model_name='cpulist',
            name='CPU',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Hardware.CPU'),
        ),
    ]
