# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-08 02:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
        ('hardware', '0002_auto_20170523_1646'),
    ]

    operations = [
        migrations.CreateModel(
            name='CPUTuning',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('simple', 'Simple'), ('normal', 'Normal'), ('aggressive', 'Aggressive')], default='normal', max_length=16)),
                ('cpuUsageTuning', models.FloatField()),
                ('dbMode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Common.DBMode')),
                ('hardwareType', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Hardware.HardwareType')),
            ],
        ),
        migrations.CreateModel(
            name='MemoryUsageTuning',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('simple', 'Simple'), ('normal', 'Normal'), ('aggressive', 'Aggressive')], default='normal', max_length=16)),
                ('memoryUsageTuning', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='NetworkInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('defaultSIGTRANLinkSpeed', models.IntegerField()),
                ('defaultSIGTRANLinkNumber', models.IntegerField()),
                ('maxSIGTRANPortUtil', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='VMType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('native', 'Native'), ('openstack', 'Openstack'), ('vmware', 'VMWare'), ('cbis', 'CBIS')], max_length=16)),
                ('capacity', models.FloatField(default=1)),
            ],
        ),
        migrations.RenameField(
            model_name='cpu',
            old_name='HTCapacityRatio',
            new_name='htCapacityRatio',
        ),
        migrations.RenameField(
            model_name='cpu',
            old_name='VMCapacityRatio',
            new_name='vmCapacityRatio',
        ),
        migrations.RenameField(
            model_name='cpuclientlist',
            old_name='CPU',
            new_name='cpu',
        ),
        migrations.RenameField(
            model_name='cpulist',
            old_name='CPU',
            new_name='cpu',
        ),
        migrations.RenameField(
            model_name='hardwareconfiguration',
            old_name='CPUNumber',
            new_name='cpuNumber',
        ),
        migrations.RenameField(
            model_name='hardwareconfiguration',
            old_name='HardwareModel',
            new_name='hardwareModel',
        ),
        migrations.RenameField(
            model_name='hardwaremodel',
            old_name='CPU',
            new_name='cpu',
        ),
        migrations.RenameField(
            model_name='hardwaremodel',
            old_name='HardwareType',
            new_name='hardwareType',
        ),
        migrations.RenameField(
            model_name='memorylist',
            old_name='CPU',
            new_name='cpu',
        ),
        migrations.AddField(
            model_name='cpu',
            name='maxDiameterPerIONode',
            field=models.IntegerField(default=120000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cpu',
            name='maxLDAPPerIONode',
            field=models.IntegerField(default=160000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cpu',
            name='maxSIGTRANPerIONode',
            field=models.IntegerField(default=40000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cpuclientlist',
            name='dbCapacityNDB',
            field=models.IntegerField(default=2000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cpuclientlist',
            name='mateCapacityNDB',
            field=models.IntegerField(default=10000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='hardwaremodel',
            name='maxSubscriberSupport',
            field=models.IntegerField(default=12000000),
            preserve_default=False,
        ),
    ]
