# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-15 06:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hardware', '0004_delete_networkinfo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hardwareconfiguration',
            name='hardwareModel',
        ),
        migrations.RenameField(
            model_name='cpu',
            old_name='hyperthreadEnabled',
            new_name='virtualizationSupported',
        ),
        migrations.RemoveField(
            model_name='cpu',
            name='defaultClientNumber',
        ),
        migrations.RemoveField(
            model_name='cpu',
            name='htCapacityRatio',
        ),
        migrations.RemoveField(
            model_name='cpu',
            name='maxDiameterPerIONode',
        ),
        migrations.RemoveField(
            model_name='cpu',
            name='maxLDAPPerIONode',
        ),
        migrations.RemoveField(
            model_name='cpu',
            name='maxSIGTRANPerIONode',
        ),
        migrations.RemoveField(
            model_name='cpu',
            name='virtualization',
        ),
        migrations.RemoveField(
            model_name='cpu',
            name='vmCapacityRatio',
        ),
        migrations.RemoveField(
            model_name='cpulist',
            name='cpu',
        ),
        migrations.RemoveField(
            model_name='memorylist',
            name='cpu',
        ),
        migrations.AddField(
            model_name='cpulist',
            name='hardwareModel',
            field=models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, to='Hardware.HardwareModel'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='hardwaremodel',
            name='defaultClientNumber',
            field=models.IntegerField(default=24),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='hardwaremodel',
            name='maxDiameterPerIONode',
            field=models.IntegerField(default=120000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='hardwaremodel',
            name='maxLDAPPerIONode',
            field=models.IntegerField(default=160000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='hardwaremodel',
            name='maxSIGTRANPerIONode',
            field=models.IntegerField(default=40000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='hardwaremodel',
            name='reservedCoreNumberForVM',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='hardwaremodel',
            name='vmCapacityRatio',
            field=models.FloatField(default=0.8),
        ),
        migrations.AddField(
            model_name='hardwaremodel',
            name='vmType',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Hardware.VMType'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='hardwaretype',
            name='isVM',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='memorylist',
            name='hardwareModel',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Hardware.HardwareModel'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='HardwareConfiguration',
        ),
    ]
