# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-16 05:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hardware', '0005_auto_20170615_1434'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cpuclientlist',
            name='cpu',
        ),
        migrations.RemoveField(
            model_name='hardwaremodel',
            name='vmType',
        ),
        migrations.AddField(
            model_name='cpulist',
            name='capacityRatio',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cpulist',
            name='clientNumber',
            field=models.IntegerField(default=24),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cpulist',
            name='dbCapacityNDB',
            field=models.IntegerField(default=2000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cpulist',
            name='mateCapacityNDB',
            field=models.IntegerField(default=1000),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='CPUClientList',
        ),
    ]
