# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-16 06:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hardware', '0006_auto_20170616_1345'),
    ]

    operations = [
        migrations.AddField(
            model_name='hardwaretype',
            name='isNDBSupport',
            field=models.BooleanField(default=True),
        ),
    ]
