# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-16 06:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hardware', '0007_hardwaretype_isndbsupport'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hardwaretype',
            name='isNDBSupport',
        ),
        migrations.AddField(
            model_name='cpu',
            name='ndbSupported',
            field=models.BooleanField(default=True),
        ),
    ]
