# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-23 03:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hardware', '0009_auto_20170616_1554'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cputuning',
            old_name='name',
            new_name='tuningOption',
        ),
    ]
