# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-09-29 08:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hardware', '0010_auto_20170623_1125'),
    ]

    operations = [
        migrations.AddField(
            model_name='hardwaretype',
            name='cpus',
            field=models.ManyToManyField(to='Hardware.CPU'),
        ),
    ]
