# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-10-19 03:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hardware', '0011_hardwaretype_cpus'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hardwaretype',
            name='cpus',
        ),
        migrations.AddField(
            model_name='hardwaremodel',
            name='name',
            field=models.CharField(default='', max_length=24),
            preserve_default=False,
        ),
    ]
