# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-11-10 08:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hardware', '0012_auto_20171019_1127'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cputuning',
            name='tuningOption',
            field=models.CharField(choices=[('Simple', 'Simple'), ('Normal', 'Normal'), ('Aggressive', 'Aggressive')], default='Normal', max_length=16),
        ),
        migrations.AlterField(
            model_name='memoryusagetuning',
            name='name',
            field=models.CharField(choices=[('Simple', 'Simple'), ('Normal', 'Normal'), ('Aggressive', 'Aggressive')], default='Normal', max_length=16),
        ),
    ]
