# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-11-13 08:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hardware', '0013_auto_20171110_1638'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vmtype',
            name='type',
            field=models.CharField(choices=[('Native', 'Native'), ('Openstack', 'Openstack'), ('VMWare', 'VMWare'), ('CBIS', 'CBIS')], max_length=16),
        ),
    ]
