# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-11-13 09:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hardware', '0014_auto_20171113_1655'),
    ]

    operations = [
        migrations.AddField(
            model_name='hardwaremodel',
            name='defaultCPUNumber',
            field=models.IntegerField(default=24),
            preserve_default=False,
        ),
    ]
