# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-11-13 09:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hardware', '0015_hardwaremodel_defaultcpunumber'),
    ]

    operations = [
        migrations.AddField(
            model_name='hardwaremodel',
            name='defaultMemory',
            field=models.IntegerField(default=128),
            preserve_default=False,
        ),
    ]
