# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-09-15 09:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Project', '0018_auto_20170915_1722'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='city',
            name='state',
        ),
        migrations.RemoveField(
            model_name='city1',
            name='province',
        ),
        migrations.AddField(
            model_name='city',
            name='province',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='Project.Province'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='city1',
            name='state',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='Project.State'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='address',
            name='city',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Project.City1'),
        ),
        migrations.AlterField(
            model_name='city',
            name='name',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='city1',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='selectp',
            name='city',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Project.City'),
        ),
    ]
