# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-08 07:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='calltype',
            name='ndbCPUUsageLimitation',
            field=models.FloatField(default=0.6),
        ),
    ]
