# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-08 08:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0002_calltype_ndbcpuusagelimitation'),
    ]

    operations = [
        migrations.AddField(
            model_name='calltype',
            name='diameterNumber',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='calltype',
            name='diameterSize',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='calltype',
            name='mateUpdateNumber',
            field=models.IntegerField(default=0),
        ),
    ]
