# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-09 07:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0003_auto_20170608_1611'),
    ]

    operations = [
        migrations.RenameField(
            model_name='featurecpuimpact',
            old_name='ccSS7In',
            new_name='ss7In',
        ),
        migrations.RenameField(
            model_name='featurecpuimpact',
            old_name='ccSS7Out',
            new_name='ss7Out',
        ),
        migrations.RemoveField(
            model_name='featurecpuimpact',
            name='reSS7InSize',
        ),
        migrations.RemoveField(
            model_name='featurecpuimpact',
            name='reSS7OutSize',
        ),
    ]
