# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-09 07:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Service', '0004_auto_20170609_1525'),
    ]

    operations = [
        migrations.AlterField(
            model_name='featurecpuimpact',
            name='featureName',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Service.FeatureName'),
        ),
    ]
