# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-15 06:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0005_auto_20170609_1548'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicationinformation',
            name='cpuCostForServer',
            field=models.FloatField(default=0.15),
        ),
        migrations.AddField(
            model_name='applicationinformation',
            name='initialDataSize',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='release',
            name='amaNumberPerGroupCall',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='release',
            name='amaSizePerBlock',
            field=models.IntegerField(default=3072),
        ),
        migrations.AddField(
            model_name='release',
            name='cPUCostForMultipleAMA',
            field=models.FloatField(default=0.4),
        ),
        migrations.AddField(
            model_name='release',
            name='counterNumberPerRecord',
            field=models.IntegerField(default=6),
        ),
        migrations.AddField(
            model_name='release',
            name='cpuCostForNormalAMA',
            field=models.FloatField(default=0.8),
        ),
    ]
