# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-16 05:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Hardware', '0006_auto_20170616_1345'),
        ('Service', '0006_auto_20170615_1434'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='callcost',
            name='cpu',
        ),
        migrations.AddField(
            model_name='callcost',
            name='hardwareModel',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Hardware.HardwareModel'),
            preserve_default=False,
        ),
    ]
