# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-16 06:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Common', '0004_auto_20170615_1434'),
        ('Service', '0007_auto_20170616_1345'),
    ]

    operations = [
        migrations.AddField(
            model_name='callcost',
            name='dbMode',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Common.DBMode'),
            preserve_default=False,
        ),
    ]
