# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-16 09:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hardware', '0009_auto_20170616_1554'),
        ('service', '0008_callcost_dbmode'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='countercost',
            name='cpu',
        ),
        migrations.AddField(
            model_name='countercost',
            name='hardwareModel',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Hardware.HardwareModel'),
            preserve_default=False,
        ),
    ]
