# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-11-17 06:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Service', '0011_currentrelease'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='calltype',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='release',
            options={'ordering': ['-sequence']},
        ),
    ]
