# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-11-22 06:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Service', '0012_auto_20171117_1433'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calltype',
            name='name',
            field=models.CharField(max_length=64, verbose_name='Call Type'),
        ),
    ]
