# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-03 12:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0013_auto_20171122_1438'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dbinformation',
            options={'ordering': ['db']},
        ),
        migrations.AlterModelOptions(
            name='dbname',
            options={'ordering': ['name']},
        ),
        migrations.AddField(
            model_name='dbinformation',
            name='rtdbOverhead',
            field=models.FloatField(default=0, verbose_name='RTDB Overhead'),
        ),
        migrations.AddField(
            model_name='dbname',
            name='isPrefixTable',
            field=models.BooleanField(default=False, verbose_name='Is Prefix Table?'),
        ),
        migrations.AddField(
            model_name='dbname',
            name='ndbRefPlaceholderRatio',
            field=models.FloatField(default=0, verbose_name='Reference Placeholder Ratio for NDB'),
        ),
        migrations.AddField(
            model_name='dbname',
            name='prefixTableIndexNumber',
            field=models.IntegerField(default=0, verbose_name='Prefix Table Index Number'),
        ),
        migrations.AlterField(
            model_name='dbinformation',
            name='mateLogSize',
            field=models.IntegerField(default=0, verbose_name='Mate Log Size'),
        ),
        migrations.AlterField(
            model_name='dbinformation',
            name='recordSize',
            field=models.IntegerField(default=0, verbose_name='Record Size'),
        ),
        migrations.AlterField(
            model_name='dbinformation',
            name='todoLogSize',
            field=models.IntegerField(default=0, verbose_name='Todo Log Size'),
        ),
        migrations.AlterField(
            model_name='dbinformation',
            name='updateTimes',
            field=models.FloatField(default=0, verbose_name='Update Times'),
        ),
    ]
