# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-03 12:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0014_auto_20171203_2006'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dbinformation',
            name='mateLogSize',
        ),
        migrations.RemoveField(
            model_name='dbinformation',
            name='rtdbOverhead',
        ),
        migrations.RemoveField(
            model_name='dbinformation',
            name='todoLogSize',
        ),
        migrations.RemoveField(
            model_name='dbinformation',
            name='updateTimes',
        ),
        migrations.AddField(
            model_name='dbname',
            name='mateLogSize',
            field=models.IntegerField(default=0, verbose_name='Mate Log Size'),
        ),
        migrations.AddField(
            model_name='dbname',
            name='rtdbOverhead',
            field=models.FloatField(default=0, verbose_name='RTDB Overhead'),
        ),
        migrations.AddField(
            model_name='dbname',
            name='todoLogSize',
            field=models.IntegerField(default=0, verbose_name='Todo Log Size'),
        ),
        migrations.AddField(
            model_name='dbname',
            name='updateTimes',
            field=models.FloatField(default=0, verbose_name='Update Times'),
        ),
    ]
