# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-03 13:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0015_auto_20171203_2013'),
    ]

    operations = [
        migrations.AddField(
            model_name='dbname',
            name='defaultGroupCounterFactor',
            field=models.FloatField(default=0, verbose_name='Default Factor for Group Counter'),
        ),
        migrations.AddField(
            model_name='dbname',
            name='defaultGroupFactor',
            field=models.FloatField(default=0, verbose_name='Default Factor for Group'),
        ),
        migrations.AddField(
            model_name='dbname',
            name='defaultMemberCounterFactor',
            field=models.FloatField(default=0, verbose_name='Default Factor for Member Counter'),
        ),
        migrations.AddField(
            model_name='dbname',
            name='defaultMemberFactor',
            field=models.FloatField(default=0, verbose_name='Default Factor for Member'),
        ),
        migrations.AlterField(
            model_name='featuredbimpact',
            name='groupImpactFactor',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='featuredbimpact',
            name='memberImpactFactor',
            field=models.FloatField(default=0),
        ),
    ]
