# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-04 12:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0016_auto_20171203_2147'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='otherapplicationinformation',
            name='release',
        ),
    ]
