# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-07 14:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0017_remove_otherapplicationinformation_release'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeatureCallTypeConfiguration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('featureApplicable', models.FloatField(default=1)),
                ('callType', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Service.CallType')),
                ('featureName', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Service.FeatureName')),
            ],
        ),
    ]
