# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-12 12:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0018_featurecalltypeconfiguration'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='countercost',
            name='cost',
        ),
        migrations.RemoveField(
            model_name='countercost',
            name='counterCostName',
        ),
        migrations.AddField(
            model_name='countercost',
            name='costBundlePerRecord',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='countercost',
            name='costCounterNumberImpact',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='countercost',
            name='costDBReadUpdatePerRecord',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='countercost',
            name='costGroupDBReadUpdatePerRecord',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='countercost',
            name='costPer24hBundle',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='countercost',
            name='costPerAppliedBucket',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='countercost',
            name='costPerAppliedUBD',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='countercost',
            name='costPerGroupSideBucket',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='countercost',
            name='costPerUnappliedBucket',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='countercost',
            name='costPerUnappliedCounterWithBasicCriteria',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='countercost',
            name='costPerUnappliedUBD',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='countercost',
            name='costTurnOnGroupBucket',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='countercost',
            name='costTurnOnUBD',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='countercost',
            name='costTurnOnUnappliedCounter',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='countercost',
            name='costTurnOnbucket',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='countercost',
            name='counterNumberPerRecord',
            field=models.IntegerField(default=6),
        ),
        migrations.AddField(
            model_name='countercost',
            name='percentageCounterNumberImpact',
            field=models.FloatField(default=0),
        ),
    ]
