# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-15 06:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Hardware', '0005_auto_20170615_1434'),
        ('Project', '0002_auto_20170608_1651'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='clientNumber',
            field=models.IntegerField(default=24),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='project',
            name='cpuNumber',
            field=models.IntegerField(default=24),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='project',
            name='hardwareModel',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Hardware.HardwareModel'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='project',
            name='memory',
            field=models.IntegerField(default=128),
            preserve_default=False,
        ),
    ]
