# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-26 06:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Project', '0004_project_vmtype'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='createTime',
            field=models.TimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='project',
            name='version',
            field=models.IntegerField(default=1),
        ),
    ]
