# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-05 06:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0005_auto_20170626_1438'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='comment',
            field=models.TextField(default=''),
        ),
    ]
