# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-10 01:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0011_auto_20170706_1636'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='name',
            field=models.CharField(default='', max_length=120),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='project',
            name='activeSubscriber',
            field=models.IntegerField(verbose_name='Active Subscriber'),
        ),
        migrations.AlterField(
            model_name='project',
            name='groupAccountNumber',
            field=models.IntegerField(verbose_name='Number of Group Account'),
        ),
        migrations.AlterField(
            model_name='project',
            name='inactiveSubscriber',
            field=models.IntegerField(verbose_name='Inactive Subscriber'),
        ),
        migrations.AlterField(
            model_name='trafficinformation',
            name='activeSubscriber',
            field=models.IntegerField(verbose_name='Active Subscriber'),
        ),
        migrations.AlterField(
            model_name='trafficinformation',
            name='callHoldingTime',
            field=models.IntegerField(default=0, verbose_name='Call Holding Time'),
        ),
        migrations.AlterField(
            model_name='trafficinformation',
            name='inactiveSubscriber',
            field=models.IntegerField(verbose_name='Inctive Subscriber'),
        ),
        migrations.AlterField(
            model_name='trafficinformation',
            name='trafficBHTA',
            field=models.FloatField(default=0, verbose_name='BHCA/BHTA'),
        ),
        migrations.AlterField(
            model_name='trafficinformation',
            name='trafficTPS',
            field=models.FloatField(default=0, verbose_name='CPS/TPS'),
        ),
    ]
