# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-08-22 08:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Hardware', '0010_auto_20170623_1125'),
        ('Project', '0014_auto_20170815_1614'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projectinformation',
            name='cpu',
        ),
        migrations.AddField(
            model_name='project',
            name='cpu',
            field=models.ForeignKey(default=48, on_delete=django.db.models.deletion.CASCADE, to='Hardware.CPU'),
            preserve_default=False,
        ),
    ]
