# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-10-12 02:22
from __future__ import unicode_literals

from django.db import migrations
import smart_selects.db_fields


class Migration(migrations.Migration):

    dependencies = [
        ('Project', '0021_auto_20171010_1619'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='hardwareType',
            field=smart_selects.db_fields.ChainedManyToManyField(chained_field='cpu', chained_model_field='cpus', horizontal=True, to='Hardware.HardwareType'),
        ),
    ]
