# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-10-19 03:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import smart_selects.db_fields


class Migration(migrations.Migration):

    dependencies = [
        ('Hardware', '0012_auto_20171019_1127'),
        ('Project', '0022_auto_20171012_1022'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='cpu',
        ),
        migrations.RemoveField(
            model_name='project',
            name='hardwareType',
        ),
        migrations.AddField(
            model_name='project',
            name='hardwareType',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Hardware.HardwareType'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='selectp',
            name='city',
            field=smart_selects.db_fields.ChainedForeignKey(auto_choose=True, chained_field='province', chained_model_field='province', help_text='Location aaa', on_delete=django.db.models.deletion.CASCADE, to='Project.City'),
        ),
    ]
