# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-10-19 03:28
from __future__ import unicode_literals

from django.db import migrations
import django.db.models.deletion
import smart_selects.db_fields


class Migration(migrations.Migration):

    dependencies = [
        ('hardware', '0012_auto_20171019_1127'),
        ('project', '0023_auto_20171019_1127'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='cpu',
            field=smart_selects.db_fields.ChainedForeignKey(auto_choose=True, chained_field='hardwareType', chained_model_field='hardwareType', default=1, on_delete=django.db.models.deletion.CASCADE, to='Hardware.HardwareModel'),
            preserve_default=False,
        ),
    ]
