# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-10-27 07:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hardware', '0012_auto_20171019_1127'),
        ('project', '0024_project_cpu'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='cpu',
        ),
        migrations.RemoveField(
            model_name='project',
            name='hardwareType',
        ),
        migrations.AddField(
            model_name='project',
            name='hardwareModel',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Hardware.HardwareModel', verbose_name='Hardware Model'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='projectinformation',
            name='memory',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Hardware.MemoryList', verbose_name='Memory'),
        ),
    ]
