# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-11-08 06:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0027_workingproject'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='name',
            field=models.CharField(max_length=120, unique=True, verbose_name='Name'),
        ),
    ]
