# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-11-10 08:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0028_auto_20171108_1415'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={'verbose_name': 'Project', 'verbose_name_plural': 'Project'},
        ),
        migrations.AlterModelOptions(
            name='projectinformation',
            options={'verbose_name': 'Project General Information', 'verbose_name_plural': 'Project General Information'},
        ),
    ]
