# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-11-22 06:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0030_auto_20171117_1433'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dbconfiguration',
            name='dbFactor',
            field=models.FloatField(default=0, verbose_name='DB Factor'),
        ),
        migrations.AlterField(
            model_name='dbconfiguration',
            name='placeholderRatio',
            field=models.FloatField(default=0, verbose_name='Placeholder Ratio (%)'),
        ),
        migrations.AlterField(
            model_name='featureconfiguration',
            name='colocateMemberGroup',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='featureconfiguration',
            name='feature',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Service.FeatureName', verbose_name='Feature Name'),
        ),
        migrations.AlterField(
            model_name='featureconfiguration',
            name='featurePenetration',
            field=models.FloatField(default=0, verbose_name='Feature Penetration (%)'),
        ),
        migrations.AlterField(
            model_name='trafficinformation',
            name='callType',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Service.CallType', verbose_name='Call Type'),
        ),
    ]
