# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-11-24 06:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Project', '0032_auto_20171122_1505'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='counterconfiguration',
            options={'verbose_name': 'Counter Configuration', 'verbose_name_plural': 'Counter Configuration'},
        ),
        migrations.AddField(
            model_name='counterconfiguration',
            name='configureForCallType',
            field=models.BooleanField(default=False, verbose_name='Configure Counter For Call Type'),
        ),
        migrations.AlterField(
            model_name='counterconfiguration',
            name='appliedBucketNumber',
            field=models.FloatField(default=0, verbose_name='Applied Bucket Number'),
        ),
        migrations.AlterField(
            model_name='counterconfiguration',
            name='appliedUBDNumber',
            field=models.FloatField(default=0, verbose_name='Applied UBD Number'),
        ),
        migrations.AlterField(
            model_name='counterconfiguration',
            name='average24hBundleNumberPerSubscriber',
            field=models.FloatField(default=0, verbose_name='Number of 24h Bundle'),
        ),
        migrations.AlterField(
            model_name='counterconfiguration',
            name='averageBundleNumberPerSubscriber',
            field=models.FloatField(default=0, verbose_name='Number of Bundle'),
        ),
        migrations.AlterField(
            model_name='counterconfiguration',
            name='generateMultipleAMAForCounter',
            field=models.BooleanField(default=False, verbose_name='Generate Multiple AMA For Counter'),
        ),
        migrations.AlterField(
            model_name='counterconfiguration',
            name='nonAppliedBucketNumber',
            field=models.FloatField(default=0, verbose_name='Non Applied Bucket Number'),
        ),
        migrations.AlterField(
            model_name='counterconfiguration',
            name='nonAppliedUBDNumber',
            field=models.FloatField(default=0, verbose_name='Non Applied UBD Number'),
        ),
        migrations.AlterField(
            model_name='counterconfiguration',
            name='turnOnBasicCriteriaCheck',
            field=models.BooleanField(default=False, verbose_name='Enable Basic Criteria Check'),
        ),
    ]
