# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-03 12:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0014_auto_20171203_2006'),
        ('project', '0033_auto_20171124_1425'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApplicationConfiguration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serverCPUCost', models.FloatField(default=0)),
                ('clientCPUCost', models.FloatField(default=0)),
                ('totalCPUCost', models.FloatField(default=0)),
                ('ss7CPUCost', models.FloatField(default=0)),
                ('tcpCPUCost', models.FloatField(default=0)),
                ('miscCPUCost', models.FloatField(default=0)),
                ('cpuBudget', models.FloatField(default=0)),
                ('ss7InSizePerSecond', models.FloatField(default=0)),
                ('ss7OutSizePerSecond', models.FloatField(default=0)),
                ('ldapSizePerSecond', models.FloatField(default=0)),
                ('diameterSizePerSecond', models.FloatField(default=0)),
                ('muTCPSize', models.FloatField(default=0)),
                ('featureLDAPSize', models.FloatField(default=0)),
                ('featureDiameterSize', models.FloatField(default=0)),
                ('memoryUsage', models.FloatField(default=0)),
                ('clientCPUUsagePercentage', models.FloatField(default=0)),
                ('dbCacheSize', models.FloatField(default=0)),
                ('spaTextSize', models.FloatField(default=0)),
                ('amaPerSecond', models.FloatField(default=0)),
                ('cpuBaseNodeNumber', models.FloatField(default=0)),
                ('memoryBaseNodeNumber', models.FloatField(default=0)),
                ('ss7BaseNodeNumber', models.FloatField(default=0)),
                ('nodeNumberNeeded', models.FloatField(default=0)),
                ('ndbMateNode', models.FloatField(default=0)),
                ('ndbRoutingNode', models.FloatField(default=0)),
                ('dbNodeNumberNeeded', models.FloatField(default=0)),
                ('ss7BaseIONodeNumber', models.FloatField(default=0)),
                ('ldapBaseIONodeNumber', models.FloatField(default=0)),
                ('diameterBaseIONodeNumber', models.FloatField(default=0)),
                ('ioNodeNumberNeeded', models.FloatField(default=0)),
                ('boundType', models.CharField(choices=[('CPU Bound', 'CPU Bound'), ('Memory Bound', 'Memory Bound')], default='CPU Bound', max_length=20, verbose_name='Bound Type')),
                ('applicationName', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Service.ApplicationName')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Project.Project')),
            ],
        ),
        # migrations.RemoveField(
        #     model_name='city',
        #     name='province',
        # ),
        # migrations.RemoveField(
        #     model_name='selectp',
        #     name='city',
        # ),
        # migrations.RemoveField(
        #     model_name='selectp',
        #     name='province',
        # ),
        migrations.AlterModelOptions(
            name='calltypecounterconfiguration',
            options={'verbose_name': 'Counter Configuration for Call Type', 'verbose_name_plural': 'Counter Configuration for Call Type'},
        ),
        # migrations.RemoveField(
        #     model_name='calltypecounterconfiguration',
        #     name='counterconfiguration_ptr',
        # ),
        # migrations.AddField(
        #     model_name='calltypecounterconfiguration',
        #     name='appliedBucketNumber',
        #     field=models.FloatField(default=0, verbose_name='Applied Bucket Number'),
        # ),
        # migrations.AddField(
        #     model_name='calltypecounterconfiguration',
        #     name='appliedUBDNumber',
        #     field=models.FloatField(default=0, verbose_name='Applied UBD Number'),
        # ),
        # migrations.AddField(
        #     model_name='calltypecounterconfiguration',
        #     name='average24hBundleNumberPerSubscriber',
        #     field=models.FloatField(default=0, verbose_name='Number of 24h Bundle'),
        # ),
        # migrations.AddField(
        #     model_name='calltypecounterconfiguration',
        #     name='averageBundleNumberPerSubscriber',
        #     field=models.FloatField(default=0, verbose_name='Number of Bundle'),
        # ),
        # migrations.AddField(
        #     model_name='calltypecounterconfiguration',
        #     name='id',
        #     field=models.AutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
        #     preserve_default=False,
        # ),
        # migrations.AddField(
        #     model_name='calltypecounterconfiguration',
        #     name='nonAppliedBucketNumber',
        #     field=models.FloatField(default=0, verbose_name='Non Applied Bucket Number'),
        # ),
        # migrations.AddField(
        #     model_name='calltypecounterconfiguration',
        #     name='nonAppliedUBDNumber',
        #     field=models.FloatField(default=0, verbose_name='Non Applied UBD Number'),
        # ),
        # migrations.AddField(
        #     model_name='calltypecounterconfiguration',
        #     name='project',
        #     field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Project.Project'),
        #     preserve_default=False,
        # ),
        migrations.AddField(
            model_name='counterconfiguration',
            name='groupBucketNumber',
            field=models.FloatField(default=0, verbose_name='Group Bucket Number'),
        ),
        migrations.AddField(
            model_name='counterconfiguration',
            name='groupBundleNumber',
            field=models.FloatField(default=0, verbose_name='Number of Group Bundle'),
        ),
        migrations.AddField(
            model_name='dbconfiguration',
            name='cacheSize',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='dbconfiguration',
            name='mateLogSize',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='dbconfiguration',
            name='recordNumber',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='dbconfiguration',
            name='recordSize',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='dbconfiguration',
            name='referenceDBFactor',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='dbconfiguration',
            name='referencePlaceholderRatio',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='dbconfiguration',
            name='subscriberNumber',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='dbconfiguration',
            name='todoLogSize',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='trafficinformation',
            name='cpuCostPerCall',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='trafficinformation',
            name='diameterSizePerSecond',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='trafficinformation',
            name='featureDiameterSize',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='trafficinformation',
            name='featureLDAPSize',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='trafficinformation',
            name='ldapSizePerSecond',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='trafficinformation',
            name='muTCPSize',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='trafficinformation',
            name='ndbCPULimitation',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='trafficinformation',
            name='serverCPUCost',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='trafficinformation',
            name='ss7CPUCost',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='trafficinformation',
            name='ss7InSizePerSecond',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='trafficinformation',
            name='ss7OutSizePerSecond',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='trafficinformation',
            name='tcpCPUCost',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='trafficinformation',
            name='totalCPUCost',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='counterconfiguration',
            name='configureForCallType',
            field=models.BooleanField(default=False, verbose_name='Configure Counter For Call Types'),
        ),
        migrations.AlterField(
            model_name='dbconfiguration',
            name='dbInfo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Service.DBInformation', verbose_name='DB Name'),
        ),
        migrations.AlterField(
            model_name='dbconfiguration',
            name='memberGroupOption',
            field=models.CharField(choices=[('Member', 'Member'), ('Group', 'Group')], default='member', max_length=10, verbose_name='DB Option'),
        ),
        migrations.AlterField(
            model_name='systemconfiguration',
            name='backupAppNodeNumberPerSystem',
            field=models.IntegerField(default=0, verbose_name='Number of Backup App Node Per System'),
        ),
        migrations.AlterField(
            model_name='systemconfiguration',
            name='backupDBNodeNumberPerSystem',
            field=models.IntegerField(default=0, verbose_name='Number of Backup DB Node Per System'),
        ),
        migrations.AlterField(
            model_name='systemconfiguration',
            name='cabinetNumberPerSystem',
            field=models.IntegerField(default=1, verbose_name='Number of Cabinet Per System'),
        ),
        migrations.AlterField(
            model_name='systemconfiguration',
            name='spareAppNodeNumberPerSystem',
            field=models.IntegerField(default=0, verbose_name='Number of Spare App Node Per System'),
        ),
        migrations.AlterField(
            model_name='systemconfiguration',
            name='spareDBNodePairNumberPerSystem',
            field=models.IntegerField(default=0, verbose_name='Number of Spare DB Node Pair Per System'),
        ),
        # migrations.DeleteModel(
        #     name='City',
        # ),
        # migrations.DeleteModel(
        #     name='Province',
        # ),
        # migrations.DeleteModel(
        #     name='SelectP',
        # ),
    ]
