# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-03 14:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0036_auto_20171203_2147'),
    ]

    operations = [
        # migrations.RemoveField(
        #     model_name='address',
        #     name='city',
        # ),
        migrations.RemoveField(
            model_name='address',
            name='country',
        ),
        migrations.RemoveField(
            model_name='address',
            name='state',
        ),
        # migrations.RemoveField(
        #     model_name='city',
        #     name='province',
        # ),
        migrations.RemoveField(
            model_name='city1',
            name='state',
        ),
        migrations.RemoveField(
            model_name='host',
            name='administrator',
        ),
        migrations.RemoveField(
            model_name='host',
            name='idc',
        ),
        migrations.RemoveField(
            model_name='idc',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='maintainlog',
            name='host',
        ),
        # migrations.RemoveField(
        #     model_name='selectp',
        #     name='city',
        # ),
        # migrations.RemoveField(
        #     model_name='selectp',
        #     name='province',
        # ),
        migrations.RemoveField(
            model_name='state',
            name='country',
        ),
        # migrations.RemoveField(
        #     model_name='calltypecounterconfiguration',
        #     name='counterconfiguration_ptr',
        # ),
        # migrations.AddField(
        #     model_name='calltypecounterconfiguration',
        #     name='appliedBucketNumber',
        #     field=models.FloatField(default=0, verbose_name='Applied Bucket Number'),
        # ),
        # migrations.AddField(
        #     model_name='calltypecounterconfiguration',
        #     name='appliedUBDNumber',
        #     field=models.FloatField(default=0, verbose_name='Applied UBD Number'),
        # ),
        # migrations.AddField(
        #     model_name='calltypecounterconfiguration',
        #     name='average24hBundleNumberPerSubscriber',
        #     field=models.FloatField(default=0, verbose_name='Number of 24h Bundle'),
        # ),
        # migrations.AddField(
        #     model_name='calltypecounterconfiguration',
        #     name='averageBundleNumberPerSubscriber',
        #     field=models.FloatField(default=0, verbose_name='Number of Bundle'),
        # ),
        # migrations.AddField(
        #     model_name='calltypecounterconfiguration',
        #     name='id',
        #     field=models.AutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
        #     preserve_default=False,
        # ),
        # migrations.AddField(
        #     model_name='calltypecounterconfiguration',
        #     name='nonAppliedBucketNumber',
        #     field=models.FloatField(default=0, verbose_name='Non Applied Bucket Number'),
        # ),
        # migrations.AddField(
        #     model_name='calltypecounterconfiguration',
        #     name='nonAppliedUBDNumber',
        #     field=models.FloatField(default=0, verbose_name='Non Applied UBD Number'),
        # ),
        # migrations.AddField(
        #     model_name='calltypecounterconfiguration',
        #     name='project',
        #     field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Project.Project'),
        #     preserve_default=False,
        # ),
        migrations.DeleteModel(
            name='Address',
        ),
        # migrations.DeleteModel(
        #     name='City',
        # ),
        migrations.DeleteModel(
            name='City1',
        ),
        migrations.DeleteModel(
            name='Country',
        ),
        migrations.DeleteModel(
            name='Host',
        ),
        migrations.DeleteModel(
            name='IDC',
        ),
        migrations.DeleteModel(
            name='MaintainLog',
        ),
        # migrations.DeleteModel(
        #     name='Province',
        # ),
        # migrations.DeleteModel(
        #     name='SelectP',
        # ),
        migrations.DeleteModel(
            name='State',
        ),
    ]
