# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-04 13:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0038_auto_20171204_2057'),
    ]

    operations = [
        # migrations.RemoveField(
        #     model_name='city',
        #     name='province',
        # ),
        # migrations.RemoveField(
        #     model_name='selectp',
        #     name='city',
        # ),
        # migrations.RemoveField(
        #     model_name='selectp',
        #     name='province',
        # ),
        # migrations.RemoveField(
        #     model_name='calltypecounterconfiguration',
        #     name='counterconfiguration_ptr',
        # ),
        migrations.AddField(
            model_name='applicationconfiguration',
            name='activeSubscriber',
            field=models.IntegerField(default=0, verbose_name='Active Subscriber'),
        ),
        migrations.AddField(
            model_name='applicationconfiguration',
            name='deployOption',
            field=models.CharField(choices=[('EPAY Node', 'EPAY Node'), ('DRouter Node', 'DRouter Node'), ('CDR Pre-Processor Node', 'CDR Pre-Processor Node'), ('eCGS Node', 'eCGS Node'), ('NTGW Node', 'NTGW Node'), ('eCTRL Node', 'eCTRL Node'), ('EPPSM Node', 'EPPSM Node'), ('GRouter Node', 'GRouter Node')], default='', max_length=30, verbose_name='Deploy Option'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='applicationconfiguration',
            name='inactiveSubscriber',
            field=models.IntegerField(default=0, verbose_name='Inctive Subscriber'),
        ),
        migrations.AddField(
            model_name='applicationconfiguration',
            name='trafficTPS',
            field=models.FloatField(default=0, verbose_name='CPS/TPS'),
        ),
        # migrations.AddField(
        #     model_name='calltypecounterconfiguration',
        #     name='appliedBucketNumber',
        #     field=models.FloatField(default=0, verbose_name='Applied Bucket Number'),
        # ),
        # migrations.AddField(
        #     model_name='calltypecounterconfiguration',
        #     name='appliedUBDNumber',
        #     field=models.FloatField(default=0, verbose_name='Applied UBD Number'),
        # ),
        # migrations.AddField(
        #     model_name='calltypecounterconfiguration',
        #     name='average24hBundleNumberPerSubscriber',
        #     field=models.FloatField(default=0, verbose_name='Number of 24h Bundle'),
        # ),
        # migrations.AddField(
        #     model_name='calltypecounterconfiguration',
        #     name='averageBundleNumberPerSubscriber',
        #     field=models.FloatField(default=0, verbose_name='Number of Bundle'),
        # ),
        # migrations.AddField(
        #     model_name='calltypecounterconfiguration',
        #     name='id',
        #     field=models.AutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
        #     preserve_default=False,
        # ),
        # migrations.AddField(
        #     model_name='calltypecounterconfiguration',
        #     name='nonAppliedBucketNumber',
        #     field=models.FloatField(default=0, verbose_name='Non Applied Bucket Number'),
        # ),
        # migrations.AddField(
        #     model_name='calltypecounterconfiguration',
        #     name='nonAppliedUBDNumber',
        #     field=models.FloatField(default=0, verbose_name='Non Applied UBD Number'),
        # ),
        # migrations.AddField(
        #     model_name='calltypecounterconfiguration',
        #     name='project',
        #     field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Project.Project'),
        #     preserve_default=False,
        # ),
        # migrations.AlterField(
        #     model_name='applicationconfiguration',
        #     name='applicationName',
        #     field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Service.ApplicationName', verbose_name='Application Name'),
        # ),
        # migrations.DeleteModel(
        #     name='City',
        # ),
        # migrations.DeleteModel(
        #     name='Province',
        # ),
        # migrations.DeleteModel(
        #     name='SelectP',
        # ),
    ]
